import React from "react";
import ShoppingCart from "./ShoppingCart";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Cart | Trendy",
  description: "Generated by create Trendy Leather",
};
const ShoppingCartPage = () => {
  return <div>
   <ShoppingCart/>
  </div>;
};

export default ShoppingCartPage;
