import { Metadata } from "next";
import React from "react";
export const metadata:Metadata={
    title:"Checkout | Trendy",
    description:"Generated by Trendy"
}
const CheckoutPage = () => {
  return <div>CheckoutPage</div>;
};

export default CheckoutPage;
