import { Metadata } from "next";
import React from "react";
import Checkout from "./Checkout";
export const metadata:Metadata={
    title:"Checkout | Trendy",
    description:"Generated by Trendy"
}
const CheckoutPage = () => {
  return <div>
    <Checkout/>
  </div>;
};

export default CheckoutPage;
