const assets = {
  images: {
    logo: require("./images/tendy-logo.png"),
    casual: require("./images/casual.png"),
    banner: require("./images/Trendy Banner.png"),
    addShoppingBag: require("./images/add-shopping-bag.png"),
    noData: require("./images/nodata.png"),
    country: require("./images/country.png"),
    socialIcon: require("./images/socialicon.png"),
    man_boot: require("./images/man-boot.png"),
    man_formal: require("./images/man-formal.png"),
    man_flat: require("./images/man-flat.png"),
    man_sandal: require("./images/man-sandal.png"),
    man_sport: require("./images/man-sport.png"),
    man_causal: require("./images/man-shoe.png"),
    man_loafer: require("./images/man-loaffer.png"),
    woman_hell: require("./images/l-formal.png"),
    woman_casual: require("./images/w-causal.png"),
    woman_sport: require("./images/w-sport.png"),
    woman_sandal: require("./images/w-sandal.png"),
    woman_boot: require("./images/w-boot.png"),
    woman_flat: require("./images/w-flat.png"),
    kid_sneakers: require("./images/kid-sneakrs.png"),
    kid_sandal: require("./images/kid-sandal.png"),
    kid_sport: require("./images/kid-sport.png"),
    trendy_chart: require("./images/trendy-chart.jpg"),
    man: require("./images/man.png"),
    women: require("./images/woman.png"),
    kids: require("./images/kid.png"),
    accessories: require("./images/accessories.png"),
    login_user: require("./images/login-user.png"),
   
  },
};

export default assets;
