// import ProductDetails from "@/components/shared/productDetails/ProductDetails";
// import { Metadata } from "next";
// import React from "react";
// type TParams={
//     params:{
//         productName:string
//     }
// }


// export const metadata: Metadata = {
//   title: "Product Details | Trendy",
//   description: "Generated by create Trendy Leather",
// };

// const ProductDetailsPage = ({params}:TParams) => {

//   console.log(params);
  
//   return (
//     <div>
//       <ProductDetails  />
//     </div>
//   );
// };

// export default ProductDetailsPage;



import ProductDetails from "@/components/shared/productDetails/ProductDetails";
import { Metadata } from "next";
import React from "react";

type TParams = {
  params: {
    productName: string;
  };
};

export const metadata: Metadata = {
  title: "Product Details | Trendy",
  description: "Generated by create Trendy Leather",
};

const ProductDetailsPage: React.FC<TParams> = ({ params }) => {
  // Replace hyphens with spaces in the product name
  //  params.productName.replace(/-/g, " ");

  // console.log("Formatted Product Name:", params);

  return (
    <div>
      <ProductDetails  />
    </div>
  );
};

export default ProductDetailsPage;

